### PR TITLE
Update BetterVoting.php

### PR DESCRIPTION
**Pull request by SilverzPlayz**

### CODE REVIEW

**Comment by JackMD** [comment]
Just one word. Stupid.

**Comment by DenielWorld** [comment]
What do you expect from a "dev"

**Comment by TwistedAsylumMC** [comment]
> 
> 
> Just one word. Stupid.

Another one word. Just no.

**Comment by DenielWorld** [comment]
kek at that rate, he could of at least proposed a PR implementing configurable messages. But oh wait, he doesn't know how :v

**Pull request closed without merging**
